/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rI2C7HO06sB
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import {
  PopoverTrigger,
  PopoverContent,
  Popover,
} from "@/components/ui/popover";
import { Calendar } from "@/components/ui/calendar";
import {
  CardDescription,
  CardTitle,
  CardHeader,
  Card,
  CardContent,
} from "@/components/ui/card";
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from "@/components/ui/table";

export function Analytics() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-white-100  px-4 md:px-6 flex items-center h-16 border-b">
        <h1 className="text-xl font-semibold">Link Performance</h1>
        <div className="ml-auto flex items-center gap-4"></div>
      </header>
      <main className="flex-1 p-4 md:p-6">
        <div className="grid gap-6">
          <div className="grid md:grid-cols-3 gap-6">
            <Card>
              <CardHeader>
                <CardDescription>Total Clicks</CardDescription>
                <CardTitle>12,345</CardTitle>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader>
                <CardDescription>Unique Clicks</CardDescription>
                <CardTitle>8,765</CardTitle>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader>
                <CardDescription>Conversion Rate</CardDescription>
                <CardTitle>15.2%</CardTitle>
              </CardHeader>
            </Card>
          </div>
          <Card>
            <CardHeader>
              <CardTitle>Tracking Links</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="border rounded-lg w-full">
                <div className="relative w-full overflow-auto">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Link Name</TableHead>
                        <TableHead>Target URL</TableHead>
                        <TableHead className="text-right">
                          Total Clicks
                        </TableHead>
                        <TableHead className="text-right">
                          Unique Clicks
                        </TableHead>
                        <TableHead className="text-right">
                          Conversion Rate
                        </TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow>
                        <TableCell className="font-medium">
                          Acme Product Page
                        </TableCell>
                        <TableCell>https://acme.com/product</TableCell>
                        <TableCell className="text-right">5,678</TableCell>
                        <TableCell className="text-right">3,456</TableCell>
                        <TableCell className="text-right">12.3%</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell className="font-medium">
                          Acme Blog Post
                        </TableCell>
                        <TableCell>https://acme.com/blog/post-123</TableCell>
                        <TableCell className="text-right">2,345</TableCell>
                        <TableCell className="text-right">1,789</TableCell>
                        <TableCell className="text-right">8.7%</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell className="font-medium">
                          Acme Pricing Page
                        </TableCell>
                        <TableCell>https://acme.com/pricing</TableCell>
                        <TableCell className="text-right">1,234</TableCell>
                        <TableCell className="text-right">987</TableCell>
                        <TableCell className="text-right">15.6%</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell className="font-medium">
                          Acme About Page
                        </TableCell>
                        <TableCell>https://acme.com/about</TableCell>
                        <TableCell className="text-right">789</TableCell>
                        <TableCell className="text-right">654</TableCell>
                        <TableCell className="text-right">9.2%</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell className="font-medium">
                          Acme Contact Form
                        </TableCell>
                        <TableCell>https://acme.com/contact</TableCell>
                        <TableCell className="text-right">456</TableCell>
                        <TableCell className="text-right">321</TableCell>
                        <TableCell className="text-right">18.4%</TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  );
}
