/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Yl9cws4fxgU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardHeader, Card, CardContent } from "@/components/ui/card"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import {CardTitle} from "@/components/ui/card";
export function AnalyticsSkeleton() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-white-100  px-4 md:px-6 flex items-center h-16 border-b">
        <h1 className="text-xl font-semibold">Link Performance</h1>
        <div className="ml-auto flex items-center gap-4"></div>
      </header>
      <main className="flex-1 p-4 md:p-6">
        <div className="grid gap-6 animate-pulse">
          <div className="grid md:grid-cols-3 gap-6">
            <Card>
              <CardHeader>
                <div className="h-4 w-24 bg-gray-200 rounded" />
                <div className="h-6 w-16 bg-gray-200 rounded mt-2" />
              </CardHeader>
            </Card>
            <Card>
              <CardHeader>
                <div className="h-4 w-24 bg-gray-200 rounded" />
                <div className="h-6 w-16 bg-gray-200 rounded mt-2" />
              </CardHeader>
            </Card>
            <Card>
              <CardHeader>
                <div className="h-4 w-24 bg-gray-200 rounded" />
                <div className="h-6 w-16 bg-gray-200 rounded mt-2" />
              </CardHeader>
            </Card>
          </div>
          <Card>
          <CardHeader>
              <CardTitle>Tracking Links</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="border rounded-lg w-full">
                <div className="relative w-full overflow-auto">
                  <Table>
                    <TableHeader>
                    <TableRow>
                        <TableHead>Link Name</TableHead>
                        <TableHead>Target URL</TableHead>
                        <TableHead className="text-right">
                          Total Clicks
                        </TableHead>
                        <TableHead className="text-right">
                          Unique Clicks
                        </TableHead>
                        <TableHead className="text-right">
                          Conversion Rate
                        </TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow>
                        <TableCell>
                          <div className="h-4 w-24 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell>
                          <div className="h-4 w-32 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="h-4 w-16 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="h-4 w-16 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="h-4 w-16 bg-gray-200 rounded" />
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>
                          <div className="h-4 w-24 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell>
                          <div className="h-4 w-32 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="h-4 w-16 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="h-4 w-16 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="h-4 w-16 bg-gray-200 rounded" />
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>
                          <div className="h-4 w-24 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell>
                          <div className="h-4 w-32 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="h-4 w-16 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="h-4 w-16 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="h-4 w-16 bg-gray-200 rounded" />
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>
                          <div className="h-4 w-24 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell>
                          <div className="h-4 w-32 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="h-4 w-16 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="h-4 w-16 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="h-4 w-16 bg-gray-200 rounded" />
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>
                          <div className="h-4 w-24 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell>
                          <div className="h-4 w-32 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="h-4 w-16 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="h-4 w-16 bg-gray-200 rounded" />
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="h-4 w-16 bg-gray-200 rounded" />
                        </TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}
